const ReorderRule = require('../models/ReorderRule');
const Inventory = require('../models/Inventory');
const PurchaseRequisition = require('../models/PurchaseRequisition');
const PurchaseOrder = require('../models/PurchaseOrder');

// @desc    Create reorder rule
// @route   POST /api/automation/reorder-rules
// @access  Private
exports.createReorderRule = async (req, res) => {
    try {
        const ruleData = {
            ...req.body,
            organizationId: req.organizationId
        };
        const rule = await ReorderRule.create(ruleData);
        res.status(201).json({ success: true, data: rule });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

// @desc    Get all rules
// @route   GET /api/automation/reorder-rules
// @access  Private
exports.getReorderRules = async (req, res) => {
    try {
        const rules = await ReorderRule.find({ organizationId: req.organizationId })
            .populate('productId', 'name sku')
            .populate('warehouseId', 'name')
            .populate('preferredSupplierId', 'name');
        res.json({ success: true, data: rules });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

// @desc    Trigger auto-reorder check
// @route   POST /api/automation/trigger
// @access  Private
exports.triggerReorderCheck = async (req, res) => {
    try {
        const organizationId = req.organizationId;
        const rules = await ReorderRule.find({ organizationId, isActive: true });

        const results = [];

        for (const rule of rules) {
            const inventory = await Inventory.findOne({
                organizationId,
                productId: rule.productId,
                warehouseId: rule.warehouseId
            });

            if (inventory && inventory.quantity <= rule.minStockLevel) {
                // Determine quantity to order
                const qtyToOrder = rule.reorderQuantity > 0
                    ? rule.reorderQuantity
                    : (rule.maxStockLevel - inventory.quantity);

                // Create Requisition (Default)
                // In a real app, check 'autoApprove' to decide if PO or PR
                const requisition = await PurchaseRequisition.create({
                    organizationId,
                    requisitionNumber: `PR-AUTO-${Date.now()}`, // Simple ID generation
                    departmentId: req.user.departmentId, // Assume triggered by authorized user
                    requestedBy: req.user._id,
                    status: 'Draft',
                    priority: 'High',
                    items: [{
                        description: 'Auto-reorder generated',
                        quantity: qtyToOrder,
                        unit: 'units', // Should fetch from product
                        estimatedUnitPrice: inventory.unitCost,
                        estimatedTotal: inventory.unitCost * qtyToOrder
                    }],
                    totalAmount: inventory.unitCost * qtyToOrder,
                    notes: `Auto-generated by Rule: ${rule.name}`
                });

                results.push({
                    rule: rule.name,
                    action: 'Created Requisition',
                    id: requisition._id
                });

                // Update rule last triggered
                rule.lastTriggeredAt = new Date();
                await rule.save();
            }
        }

        res.json({
            success: true,
            message: `Check completed. ${results.length} actions taken.`,
            data: results
        });
    } catch (error) {
        console.error('Automation Trigger Error:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};
